.github/workflows/node-ci.yaml, docs/todo.md
This Pull Request create a github actions pipeline for jest tests
=> chore: create a github actions pipeline for jest tests

src/controllers/Panel.ts
This Pull Request improve the CreatePanel UseCase.
close #10
=> refact: improve CreatePanel

package-lock.json, package.json, tsconfig.json
This pull request aims to setup [Inversify Js](https://github.com/inversify/InversifyJS) js for [IoC](https://en.wikipedia.org/wiki/Inversion_of_control)
Close #27
=> chore: setup inversify for IoC

src/infra/Memory/Panel/Repositories/PanelRepository.ts, src/inversify.config.ts, src/routes/Panel.ts, src/types.ts
* **Summary of Change 1: Configuration File Addition**
Added a new configuration file called inversify.config.ts for better organization and modularity.
* **Summary of Change 2: Improving PanelRepository**
Modified the PanelRepository to be injectable and updated its constructor to use the @inject() decorator, resulting in a more efficient way to manage dependencies.
* **Summary of Change 3: Update Panel Route Instance Retrieval**
Revised the process of obtaining a panel repository instance in the routes/Panel file by using the Container class instead of the "new" keyword. This change ensures that the expected object type is returned when calling the `get` method on the Container.
* **Summary of Change 4: Introduction of Types Constant**
Implemented a types constant containing symbols …
=> feat: ioc for panel repository

package-lock.json, package.json, src/controllers/Panel.ts, src/domains/Panel/UseCases/CreatePanel.ts, src/routes/Panel.ts, tests/controllers/panel.test.ts
This PR modifies Panel Controller to use Async Handler, from Express.
----
Close #32
=> chore: use of async-handler

.gitignore, docs/todo.md, src/controllers/Panel.ts, src/domains/Panel/DTO/PanelData.ts, src/domains/Panel/Entities/Panel.ts, src/domains/Panel/UseCases/CreatePanel.ts, tests/controllers/panel.test.ts, tests/domains/Panel/useCases/CreatePanel.test.ts
This Pull Request aims to add the createdAt field to Panel.
Close #35
=> feat(Panel): add createdAt field

docs/todo.md, src/domains/Panel/Repositories/PanelRepository.ts, src/domains/Panel/UseCases/Response/UpdatePanelResponse.ts, src/domains/Panel/UseCases/Response/UpdateSuccessfulResponse.ts, src/domains/Panel/UseCases/UpdatePanel.ts, src/infra/Memory/Panel/Repositories/PanelRepository.ts, tests/domains/Panel/useCases/CreatePanel.test.ts, tests/domains/Panel/useCases/Response/UpdatePanelResponse.test.ts, tests/domains/Panel/useCases/UpdatePanel.test.ts, tests/infra/Memory/Panel/Repositories/PanelRepository.test.ts
* **Create Panel (set password for admin and optional access)**
- Improved store response test
- Added Presenter to store Controller
* **Edit Panel -> Adjusted tests**
* **Delete Panel -> Panel Archiving -> Panel Visualization... etc.**
- No changes made, only the title was updated in the list
* **Added a test for updating an existing panel**
* **Changed the return value of findBySlug when no Panel is found**
- Return value changed from undefined to null
___
Close #41 
---
> ⏳ What The Diff is processing your pull request, please stand by...
=> feat(Panel): update

docs/todo.md, src/domains/Panel/Repositories/PanelRepository.ts, src/domains/Panel/UseCases/DeletePanel.ts, src/domains/Panel/UseCases/Response/DeletePanelErrorResponse.ts, src/domains/Panel/UseCases/Response/DeletePanelResponse.ts, src/infra/Memory/Panel/Repositories/PanelRepository.ts, tests/domains/Panel/useCases/CreatePanel.test.ts, tests/domains/Panel/useCases/DeletePanel.test.ts, tests/infra/Memory/Panel/Repositories/PanelRepository.test.ts
* **Implemented Panel Deletion**
Added the ability to delete panels, complete with necessary response handling and error management.
* **Updated Panel Repository**
Enhanced the panel storage system to support the deletion feature.
* **Comprehensive Testing**
Included tests to ensure proper functionality, confirming that existing panels can be accurately deleted by their unique identifier (slug).
close #45
=> feat(Panel): delete implementation

docs/todo.md, src/controllers/PanelController.ts, src/domains/Panel/UseCases/UpdatePanel.ts, tests/controllers/panel.test.ts, tests/domains/Panel/useCases/UpdatePanel.test.ts
* **Update useCase handle**
Include the owner in the update useCase handle
Close #49
=> fix(panel): validate owner on update

docs/todo.md, src/controllers/PanelController.ts, src/domains/Panel/UseCases/Response/ShowPanelErrorResponse.ts, src/domains/Panel/UseCases/Response/ShowPanelResponse.ts, src/domains/Panel/UseCases/ShowPanel.ts, src/routes/Panel.ts, tests/controllers/panel.test.ts, tests/domains/Panel/useCases/Response/ShowPanelResponse.test.ts, tests/domains/Panel/useCases/ShowPanel.test.ts
This Pull Request aims to implement the feature to show panel in the kudos board.
Close #53
=> feat(Panel): add show feature

docs/todo.md, src/controllers/PanelController.ts, src/routes/Panel.ts, tests/controllers/panel.test.ts
This pull request aims to change the index method to show.
Close #55
=> fix(Panel): change index to show

docs/todo.md, src/controllers/PanelController.ts, src/domains/shared/presenters/PanelPresenter.ts, src/routes/Panel.ts, tests/controllers/panel.test.ts, tests/domains/shared/presenters/PanelPresenter.test.ts
This PR exposes PanelPresenter dependency in PanelController.
Closes #57
=> fix(panel): expose PanelPresenter dependency in PanelController

tests/domains/Panel/useCases/ArchivePanel.test.ts, tests/domains/Panel/useCases/CreatePanel.test.ts, tests/domains/Panel/useCases/DeletePanel.test.ts, tests/domains/Panel/useCases/UpdatePanel.test.ts
This Pull Request aims to substiture thrown word over return.
Close #63
=> fix(test): return over thrown

src/domain/Kudos/DTO/KudosData.ts, src/domain/Kudos/Entities/Kudos.ts, src/domain/Kudos/Repositories/KudosRepository.ts, src/domain/Kudos/UseCases/CreateKudos.ts, src/domain/Kudos/UseCases/Responses/CreateKudosResponse.ts, src/domain/Kudos/UseCases/Responses/ErrorResponse.ts, src/domain/Kudos/UseCases/Responses/SuccessfulResponse.ts, tests/domains/Kudos/entities/Kudos.test.ts, tests/domains/Kudos/useCases/CreateKudos.test.ts, tests/domains/Kudos/useCases/Response/CreatePanelResponse.test.ts, tests/domains/Kudos/useCases/Response/ErrorResponse.test.ts, tests/domains/Kudos/useCases/Response/SuccessfulResponse.test.ts
This pull request aims to add kudos to project with create operation
Close #70
=> Feat create kudos

src/domain/Kudos/UseCases/Responses/ShowKudosErrorResponse.ts, src/domain/Kudos/UseCases/Responses/ShowKudosResponse.ts, src/domain/Kudos/UseCases/ShowKudos.ts, src/domain/Panel/UseCases/Response/ShowPanelResponse.ts, tests/domains/Kudos/useCases/Response/ShowPanelResponse.test.ts, tests/domains/Kudos/useCases/ShowKudos.test.ts, tests/domains/Panel/useCases/ShowPanel.test.ts
This pull request aims to add show operation for Kudos.
close #72
=> Add show operation for kudos

src/domain/Kudos/UseCases/DeleteKudos.ts, src/domain/Kudos/UseCases/Responses/DeleteKudosErrorResponse.ts, src/domain/Kudos/UseCases/Responses/DeleteKudosResponse.ts, tests/domains/Kudos/useCases/DeleteKudos.test.ts
This Pull Request aims to add delete operation for Kudos
close #73
=> Add delete operation to Kudos

src/domain/Kudos/UseCases/ArchiveKudos.ts, src/domain/Kudos/UseCases/Responses/ArchiveKudosErrorResponse.ts, src/domain/Kudos/UseCases/Responses/ArchiveKudosResponse.ts, tests/domains/Kudos/useCases/ArchiveKudos.test.ts
This Pull Request aims to add Archive operation to Kudos
Close #74
=> Add archive operation to Kudos

docs/todo.md, src/domain/Panel/DTO/UpdatePanelData.ts, src/domain/Panel/UseCases/UpdatePanel.ts, tests/domains/Kudos/useCases/ArchiveKudos.test.ts, tests/domains/Kudos/useCases/UpdateKudos.test.ts, tests/domains/Panel/useCases/ArchivePanel.test.ts, tests/domains/Panel/useCases/CreatePanel.test.ts, tests/domains/Panel/useCases/DeletePanel.test.ts, tests/domains/Panel/useCases/ShowPanel.test.ts, tests/domains/Panel/useCases/UpdatePanel.test.ts
* **To-Do List Update**
The `todo.md` file has been trimmed down with some tasks being checked off.
* **Panel Title Customization**
The title property within the `UpdatePanelData.ts` file is now optional, providing users with more flexibility when creating or updating panel data.
* **Enhanced Validation Process**
The code within `UpdatePanel.ts` has been restructured. The validation process now occurs after updating panel data, making sure that the updates comply with our set rules and regulations.
* **Refactored Test Files**
Several adjustments and optimizations were made to streamline the code in test files including `ArchiveKudos.test.ts`, `UpdateKudos.test.ts`, and different Panel-related test files such as `ArchivePanel.test.ts`, `CreatePanel.test.ts`, `DeletePanel.test.ts`, …
=> Use repository interface instead memory in tests

docs/http-client.md, docs/panel.json, docs/todo.md, package.json, src/domain/Panel/Entities/Panel.ts, src/domain/Panel/Repositories/PanelRepository.ts, src/domain/Panel/UseCases/CreatePanel.ts, src/infra/MongoDB/Repositories/PanelRepository.ts, src/infra/MongoDB/models/Panel.ts, src/infra/MongoDB/services/Collection.ts, src/infra/MongoDB/services/Database.ts, src/infra/adapters/Express/controllers/KudosController.ts, src/infra/adapters/Express/controllers/PanelController.ts, src/infra/adapters/Express/routes/Kudos.ts, src/infra/inversify.config.ts, tests/domains/Panel/useCases/CreatePanel.test.ts, tests/infra/Memory/Panel/Repositories/PanelRepository.test.ts, tests/infra/adapters/Express/controllers/panel.test.ts
This PR introduces several changes, mainly aimed at enhancing the security of panels, enabling management of panels, and testing improvements. Here's a simplified breakdown:
* **Improved API for Managing Panels**: The `Panel` class now includes an `updatedAt` property, allowing to track when the last change on a panel occurred. (`Panel.ts`)
* **Created Panel Repository**: A new `PanelRepository` class, combined with a new `Collection` class allows interacting with stored panels, supporting `find` and `create`. (`PanelRepository.ts`; `Collection.ts`)
* **Enriched Panel Creation Flow**: Changes in the `create` method in `CreatePanel.ts` now guarantees it's asynchronous and employs validation for the `clientPassword` field.
* **Introduction of Database Class**: A new Database class offers …
=> Add mongodb repositories

.env.example, docs/kudos.json, docs/panel.json, docs/todo.md, src/domain/Kudos/Presenters/KudosPresenter.ts, src/domain/Kudos/Repositories/KudosRepository.ts, src/domain/Kudos/UseCases/ArchiveKudos.ts, src/domain/Kudos/UseCases/CreateKudos.ts, src/domain/Kudos/UseCases/DeleteKudos.ts, src/domain/Kudos/UseCases/ShowKudos.ts, src/domain/Kudos/UseCases/UpdateKudos.ts, src/infra/MongoDB/Repositories/KudosRepository.ts, src/infra/MongoDB/models/Kudos.ts, src/infra/adapters/Express/controllers/KudosController.ts, src/infra/adapters/Express/routes/Kudos.ts, src/infra/inversify.config.ts, src/infra/types.ts, tests/domains/Kudos/useCases/ArchiveKudos.test.ts, tests/domains/shared/presenters/KudosPresenter.test.ts, tests/infra/adapters/Express/controllers/kudos.test.ts
* **Addition of Kudos Feature Files**
A `KudosPresenter.ts` file has been introduced into the project. This acts as a bridge between the data (Kudos in this case) and how it's presented to the user.
* **Improvements on Kudos Repository File**
Updates have been made to `KudosRepository.ts` file to help manage 'kudos' data more effectively. This change allows better creation, update, and deletion of 'kudos' by using 'Promises' - a way to handle tasks that may take time to complete.
* **Enhancements in Kudos-related Use Cases**
Files like `ArchiveKudos.ts`, `CreateKudos.ts`, `DeleteKudos.ts`, `ShowKudos.ts`, and `UpdateKudos.ts` are updated to handle the 'kudos' data more effectively and to be faster, using a technique called async/await.
* **Creation of Infrastructure for the Kudos …
=> feat(Kudos): mongodb and controller

src/infra/adapters/Express/routes/Kudos.ts
This Pull Request aims to create routes for:
- update
- show
- archive
=> fix(Kudos): create routes

src/domain/Kudos/UseCases/UpdateKudos.ts, src/domain/Panel/UseCases/UpdatePanel.ts, src/domain/shared/errors/InvalidStatus.ts, src/infra/adapters/Express/controllers/PanelController.ts, tests/domains/Kudos/useCases/UpdateKudos.test.ts, tests/domains/Panel/useCases/UpdatePanel.test.ts
- Validate panel status before update it
- Validate kudos status before update it
Close #62
=> Chore: remove technical debts

src/domain/Kudos/UseCases/UpdateKudos.ts, tests/domains/Kudos/useCases/UpdateKudos.test.ts, tests/infra/adapters/Express/controllers/kudos.test.ts
Permitir que o dono do painel alterar os kudos
close #80
=> feat(Kudos): allow panel owner do update kudos

src/domain/Kudos/UseCases/ArchiveKudos.ts, src/infra/adapters/Express/routes/Kudos.ts, tests/domains/Kudos/useCases/ArchiveKudos.test.ts, tests/domains/Kudos/useCases/UpdateKudos.test.ts, tests/infra/adapters/Express/controllers/kudos.test.ts
This Pull Request aims to allow panel's owner to archive its kudos
Close #83
=> feat(Kudos): panels owner to archive kudos

src/domain/Kudos/UseCases/DeleteKudos.ts, tests/domains/Kudos/useCases/DeleteKudos.test.ts, tests/infra/adapters/Express/controllers/kudos.test.ts
This pull request aims to allow panel owner to delete kudos from it
Close #101
=> feat(Kudos): panels owner to delete kudos

src/domain/Kudos/Presenters/KudosPresenter.ts, src/domain/Kudos/Repositories/KudosRepository.ts, src/domain/Kudos/UseCases/ListKudos.ts, src/domain/shared/Responses/ListDataResponse.ts, src/infra/MongoDB/Repositories/KudosRepository.ts, src/infra/adapters/Express/controllers/KudosController.ts, src/infra/adapters/Express/routes/Kudos.ts, tests/domains/Kudos/useCases/ArchiveKudos.test.ts, tests/domains/Kudos/useCases/CreateKudos.test.ts, tests/domains/Kudos/useCases/DeleteKudos.test.ts, tests/domains/Kudos/useCases/ListKudos.test.ts, tests/domains/Kudos/useCases/ShowKudos.test.ts, tests/domains/Kudos/useCases/UpdateKudos.test.ts, tests/domains/shared/Responses/ListDataResponse.test.ts, tests/domains/shared/presenters/KudosPresenter.test.ts, tests/infra/MongoDB/Repositories/KudosRepository.test.ts, tests/infra/adapters/Express/controllers/kudos.test.ts
This pull request aim to implement a feature to kudos to list all from a provided panel slug.
Close #79
=> feat(Kudos): list all kudos from a panel

.env.example, docker-compose.yml
Este Pull Request altera o docker compose para ter um comando que sobe a aplicação node ao rodar o projeto.
=> chore(Docker): add command to compose

.docker/build/app/Dockerfile, .docker/build/app/entrypoint.sh, docker-compose.yml, docs/todo.md, scripts/pre-commit, src/infra/adapters/Express/controllers/AuthController.ts, src/infra/adapters/Express/controllers/PanelController.ts, src/infra/adapters/Express/routes/Kudos.ts
* **Introduction of Security Layer to Kudos Routes**
For enhancing the security, a new middleware has been added to the 'Kudos' function. This will ensure that access is granted only when the Bearer authentication is confirmed, thereby adding a more stringent layer of protection against unauthorized access.
* **Modification in Authentication Control Response Format**
The response mechanism in the Authentication Controller has been altered. Previously, it would send an entire object with "ok" and "token" properties. However, it has now been simplified to send just the token, which leads to a more streamlined and less complex response process.
=> feat: add auth middleware to kudos routes
